# Generated by Django 5.0.1 on 2024-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swits',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
