# Generated by Django 5.0.1 on 2024-01-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switterapp', '0003_alter_swits_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swits',
            name='likes',
        ),
    ]
