# Generated by Django 5.0.1 on 2024-02-07 14:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switterapp', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='swits',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
